# PODNAME: Database::Accessor::Manual
# ABSTRACT: What is Database::Accessor, and how do I use it?

=pod

=head1 Datatbase::Accessor is not an ORM

=head1 Table Of Contents

=for :list
* L<Database::Accessor::Tutorial::GettingStarted>
* L<Database::Accessor::Tutorial::Basics>


=pod

=head1 NAME

Database::Accessor::Manual - The index of the Manual

=head1 Description 

Here is where you can find all the documention for Database::Accessor or DA for short.  DA, as the name implies, is just a simple accesslayer for your data,
it works in conjunction with a DAD (Databacse::Accessor::Driver) is intended to access
=head1 Datatbase::Accessor is not an ORM

=head1 Table Of Contents

=for :list
* L<Database::Accessor::Tutorial::GettingStarted>
* L<Database::Accessor::Tutorial::Basics>

Database::Accessor::Tutorial::GettnigStarted

    A quick document on what you will need to get Accessor working with a few examples of its usage, i.e. you will need a DB and the following schema. 

Database::Accessor::Tutorial::Basics

    A document that will introduce the two most basic parts of Accessor 'View' and 'Elements' collection, the five control flags, and the four CRUD functions on a static DA.

Database::Accessor::Tutorial::Conditions

    This document will expand on the basics by introducing the concept of a 'predicate' in the way of a simple 'condition' and also introduce the 'Param' element.

Database::Accessor::Tutorial::BasicDynamic

    This document will add in the concept of dynamic attributes for the Elements and 'conditions'

Database::Accessor::Tutorial::Links

    This POD will introduce the concept of a link.

Database::Accessor::Manual::MoreElements

    This POD will look at the basic usage of Functions and Expressions in the elements Array

Database::Accessor::Tutorial::Sorts

    This POD will look at the rather basic topic of the Sorts attribute

Database::Accessor::Tutorial::GatherFilter

    This POD will introduce the more advanced topic of Gathers and Filters.

Database::Accessor::Tutorial::AdvancedElements

    This POD will look at element Aggregates with Gather and Filters. mixing function, expression and other elements in advanced predicates

Database::Accessor::Tutorial::AdvancedConditions

    This POD will look at multi predicate conditions, functions and expression in conditions and an special conditions like 'IN' 

Database::Accessor::Tutorial::AdvancedLinks

    This POD will look at using multiple links on a view, functions and expression on a link and multiple predicates on a link

Database::Accessor::Manual::Basics

    The four crud expressions explianed and the 5 control flags.

Database::Accessor::Manual::Attributes

    A listing of all the attributres

Database::Accessor::Manual::Methods

    A listing of all the methods

Database::Accessor::Manual::View

    A detailed look at the view

Database::Accessor::Manual::Element

    A detailed look at the Element Class and its various incarnations

Database::Accessor::Manual::Predicate

    A detailed look at the Predicate Class

Database::Accessor::Manual::Condition

    A detailed look at the Condition Class

Database::Accessor::Manual::Link

    A detailed look at the Link Class

Database::Accessor::Manual::Sort

    A detailed look at the Sort Class

Database::Accessor::CookBook

    a place for all the cool stuff that doesn't have a place above

Database::Accessor::Driver::WritersGuide

A doc for people who are fool hardy enough to try and write a DAD

=cut 
