# PODNAME: Database::Accessor::Tutorial
# ABSTRACT: Want to learn Database::Accesor! Here is the place to start

=pod

=head1 Description

This is a tutorial for Database::Accessor or DA for short.  DA is a CRUD (Create, Retreive, Update Delete) layer for any DB. 
If you are looking for all sorts of neat accessors and methors for you classes look elsewhere, as DA is not an ORM.  If
you just a neat little backend for a set of classes DA is for you.  I you also have to face using both an SQL DB and a Non-SQL like Mongo i nthe same projectand want only 
one backend then DA is for you.

This tutorial should give you all you need to get you started with DA.

=head1 Sections

=for :list

* L<Database::Accessor::Tutorial::Concepts>

* L<Database::Accessor::Tutorial::GettingStarted>
A quick document on what you will need to get DA up and working



Database::Accessor::Tutorial::GettnigStarted


Database::Accessor::Tutorial::Basics

    A document that will introduce the two most basic parts of Accessor 'View' and 'Elements' collection, the five control flags, and the four CRUD functions on a static DA.

Database::Accessor::Tutorial::Conditions

    This document will expand on the basics by introducing the concept of a 'predicate' in the way of a simple 'condition' and also introduce the 'Param' element.

Database::Accessor::Tutorial::BasicDynamic

    This document will add in the concept of dynamic attributes for the Elements and 'conditions'

Database::Accessor::Tutorial::Links

    This POD will introduce the concept of a link.

Database::Accessor::Manual::MoreElements

    This POD will look at the basic usage of Functions and Expressions in the elements Array

Database::Accessor::Tutorial::Sorts

    This POD will look at the rather basic topic of the Sorts attribute

Database::Accessor::Tutorial::GatherFilter

    This POD will introduce the more advanced topic of Gathers and Filters.

Database::Accessor::Tutorial::AdvancedElements

    This POD will look at element Aggregates with Gather and Filters. mixing function, expression and other elements in advanced predicates

Database::Accessor::Tutorial::Advancedconditions

    This POD will look at multi predicate conditions, functions and expression in conditions and an special conditions like 'IN' 

Database::Accessor::Tutorial::AdvancedLinks

    This POD will look at using multiple links on a view, functions and expression on a link and multiple predicates on a link

Database::Accessor::Manual::Basics

    The four crud expressions explianed and the 5 control flags.

Database::Accessor::Manual::Attributes

    A listing of all the attributres

Database::Accessor::Manual::Methods

    A listing of all the methods

Database::Accessor::Manual::View

    A detailed look at the view

Database::Accessor::Manual::Element

    A detailed look at the Element Class and its various incarnations

Database::Accessor::Manual::Predicate

    A detailed look at the Predicate Class

Database::Accessor::Manual::Condition

    A detailed look at the Condition Class

Database::Accessor::Manual::Link

    A detailed look at the Link Class

Database::Accessor::Manual::Sort

    A detailed look at the Sort Class

Database::Accessor::CookBook

    a place for all the cool stuff that doesn't have a place above

Database::Accessor::Driver::WritersGuide

A doc for people who are fool hardy enough to try and write a DAD


=cut 
